lists/urls.py
from django.urls import path
from . import views


app_name = 'lists'

urlpatterns = [
    path('<int:list_id>/', views.list_view, name='list_view'),
    path('new/', views.new_list, name='new_list'),
    path('<int:list_id>/add/', views.add_item, name='add_item'),
]

superlists/urls.py
from django.contrib import admin
from django.urls import path, include
from lists.views import home_page


urlpatterns = [
    path('admin/', admin.site.urls),

    path('lists/', include('lists.urls')),
    path('', home_page, name='home_page'),
]

lists/models.py
from django.db import models


class List(models.Model):
    pass


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, on_delete=models.CASCADE, default=None)

lists/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item, List


def home_page(request):
    return render(request, 'lists/home.html')


def list_view(request, list_id):
    list_ = List.objects.get(id=list_id)
    items = Item.objects.filter(list=list_)
    return render(request, 'lists/list.html', {'items': items, 'list': list_})


def new_list(request):
    list_ = List.objects.create()
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect('lists:list_view', list_id=list_.id)


def add_item(request, list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'], list=list_)
    return redirect('lists:list_view', list_id=list_.id)

lists/templates/lists/home.html
<html>
<head>
    <title>To-Do Lists</title>
</head>
<body>
    <h1>Start a new To-Do list</h1>

    <div>
        <form method="post" action="/lists/new/">
            {% csrf_token %}
            <input type="text" id="id_new_item" name="item_text" placeholder="Enter a to-do item">
        </form>
    </div>

    <div>
        <table id="list-table">
            {% for item in items %}
                <tr><td>{{ forloop.counter }}: {{ item.text }}</td><tr>
            {% endfor %}
        </table>
    </div>
</body>
</html>

lists/templates/lists/list.html
<html>
<head>
    <title>To-Do Lists</title>
</head>
<body>
    <h1>Your To-Do list</h1>

    <div>
        <form method="post" action="{% url 'lists:add_item' list_id=list.id %}">
            {% csrf_token %}
            <input type="text" id="id_new_item" name="item_text" placeholder="Enter a to-do item">
        </form>
    </div>

    <div>
        <table id="list-table">
            {% for item in items %}
                <tr><td>{{ forloop.counter }}: {{ item.text }}</td><tr>
            {% endfor %}
        </table>
    </div>
</body>
</html>